time:
  amount: "1s"

database:
    bucket: "test-bucket"
    host: "http://localhost:8086"
    token: "AS1e3YTxMnPWjVJBHF_weii6bKG1lXJKJHRTriVY-z8PUq71zJLRnn7pG7YXzqJ1lbyo4yPQc3KC8b94fjZAiA=="
    org: "acs-dev"

